export const DEMO_USERS = [
  {
    reference_id: 'ADMIN',
    name: 'Admin',
    email: 'admin@novaworks.example',
    password: 'admin123',
    role: 'ADMIN',
    specialization: 'Administration',
    skills: ['Company overview', 'Transcript creation'],
  },
  {
    reference_id: 'PM01',
    name: 'Ayesha Khan',
    email: 'ayesha@novaworks.example',
    password: 'Demo123!',
    role: 'MANAGER',
    specialization: 'Web PM',
    skills: ['Web projects', 'Client coordination'],
  },
  {
    reference_id: 'PM02',
    name: 'Bilal Ahmed',
    email: 'bilal@novaworks.example',
    password: 'Demo123!',
    role: 'MANAGER',
    specialization: 'Mobile PM',
    skills: ['Mobile projects', 'Delivery planning'],
  },
  {
    reference_id: 'PM03',
    name: 'Hina Malik',
    email: 'hina@novaworks.example',
    password: 'Demo123!',
    role: 'MANAGER',
    specialization: 'AI PM',
    skills: ['AI projects', 'Requirement review'],
  },
  {
    reference_id: 'DEV01',
    name: 'Ali Raza',
    email: 'ali@novaworks.example',
    password: 'Demo123!',
    role: 'AGENT',
    specialization: 'Full-Stack Developer',
    skills: ['React', 'Frontend integration'],
  },
  {
    reference_id: 'DEV02',
    name: 'Hamza Shah',
    email: 'hamza@novaworks.example',
    password: 'Demo123!',
    role: 'AGENT',
    specialization: 'Full-Stack Developer',
    skills: ['Node.js', 'Databases', 'APIs'],
  },
  {
    reference_id: 'DEV03',
    name: 'Sara Noor',
    email: 'sara@novaworks.example',
    password: 'Demo123!',
    role: 'AGENT',
    specialization: 'App Developer',
    skills: ['Flutter', 'Mobile UI'],
  },
  {
    reference_id: 'DEV04',
    name: 'Usman Tariq',
    email: 'usman@novaworks.example',
    password: 'Demo123!',
    role: 'AGENT',
    specialization: 'App Developer',
    skills: ['Flutter', 'Integration', 'Testing'],
  },
  {
    reference_id: 'DEV05',
    name: 'Zain Abbas',
    email: 'zain@novaworks.example',
    password: 'Demo123!',
    role: 'AGENT',
    specialization: 'AI Developer',
    skills: ['LLMs', 'Extraction', 'Prompts'],
  },
  {
    reference_id: 'DEV06',
    name: 'Maryam Asif',
    email: 'maryam@novaworks.example',
    password: 'Demo123!',
    role: 'AGENT',
    specialization: 'AI Developer',
    skills: ['Retrieval', 'Document processing'],
  },
] as const;
